### ISSUE TITLE
localStorage no longer persistent after update to electron 2.0.2

### ISSUE THREAD

**Issue by okwme** [electron/spectron#299]
localstorage remains persistent in actual use of the app but is not persistent when running e2e tests with spectron. before updating to electron 2.0.2 this still worked.

**Comment by MarshallOfSound** [comment]
It looks like you didn't fill out our [Issue Template](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md), please ensure you provide all information requested in the issue template so that we can try to help you out.

In the future issues you create without the template will be closed, you can find the issue template [here](https://raw.githubusercontent.com/electron/electron/master/.github/ISSUE_TEMPLATE.md) and it is automatically populated in the new issue form.

**Comment by okwme** [comment]
sorry about that, started following the issue template and created a dummy project to display the error but realized it was a problem with my chromeDriver. Reinstalling node_modules fixed the problem.
