### ISSUE TITLE
How to emulate offline mode

### ISSUE THREAD

**Issue by Michenux** [electron/spectron#315]
Hi,

Has anybody succeeded in emulating offline mode with spectron ?
I would like to have a code sample.

Thx

**Comment by codebytere** [comment]
Thanks for reaching out!

We close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
