### ISSUE TITLE
electron.remote.require returns empty object

### ISSUE THREAD

**Issue by fantasticsid** [electron/spectron#62]
I'm trying to remote require a module from renderer process, the module itself is from the main process.

However it seems app.electron.remote.require('./main_proc_module') returns a promise that resolves to an empty object.

Can I use remote require with spectron?

**Comment by kevinsawicki** [comment]
> Can I use remote require with spectron?

You should be able to but it will only return values that are `JSON` serializable and you won't be able to call functions on it (since they aren't JSON-serializable).

You might want to use `execute` to do this instead:

```js
app.client.execute(function () {
  //This function runs in the renderer process windo
  return require('electron').remote.require('./main_proc_modules').foo()
}).then(function (response) {
  // Runs inside your spec process
})
```

You can register it as a command via `addCommand` if it is something you want to reuse across multiple specs:

http://webdriver.io/api/utility/addCommand.html
http://webdriver.io/api/protocol/execute.html
http://webdriver.io/api/protocol/executeAsync.html

Closing this out.
