### ISSUE TITLE
What should expect for windows and linux for var app = new Application({   path: '/Applications/MyApp.app/Contents/MacOS/MyApp' })

### ISSUE THREAD

**Issue by xelfe** [electron/spectron#67]
Hi. I would like to know what is suppose to remplace this part below for windows and linux;
`var app = new Application({
  path: '/Applications/MyApp.app/Contents/MacOS/MyApp'
})`

**Comment by kevinsawicki** [comment]
@xelfe it will be the path to the main executable.

So it would be something like `C:/Users/kevin/Downloads/MyApp/myapp.exe` on Windows and something like `/home/kevin/Downloads/MyApp/myapp` on Linux.

It is different for every application since name styles vary but it will be the path that you launch when you run the app normally.

Closing this out.
